### ISSUE TITLE
Run PowerShell Script in Azure hosted Ubuntu agent

### ISSUE THREAD

**Issue by yzhaopost** [anmason/AzureDevOpsHelps#1]
I have a PowerShell task in my release pipeline. The agent is Azure hosted Ubuntu 1604. Since the PowerShell 6.2.0 comes with the hosted ubuntu (https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/linux/Ubuntu1604-README.md), I am trying to run your script (with filled information). Unfortunately, I get "findstr : the term 'findstr' is not recognized as the name of a cmdlet, function, script file, or operable program..." error. Looks like it can not recognize the PowerShell command in the hosted Ubuntu. Is this a path issue? or something? Any suggestions would be greatly appreciated.

**Comment by anmason** [comment]
@yzhaopost I just uploaded a [bash version](https://github.com/anmason/AzureDevOpsHelps/blob/master/Pipelines/UploadSingleFileToGitHub/uploadToGitHub.sh) of the script. Can you try using that with a bash task instead of the PowerShell script/task?

**Comment by yzhaopost** [comment]
Your bash version works great! Thank you!

**Comment by anmason** [comment]
Awesome! I'll go ahead and close this Issue then.
